#ifndef GVVPEGERWGGKARJPYNASCTHRTEGFYQYQBSXOROAEYBYUAXDLCNUXKGJJELBQCUJP
#define GVVPEGERWGGKARJPYNASCTHRTEGFYQYQBSXOROAEYBYUAXDLCNUXKGJJELBQCUJP
#include "mainFrame.h"
#include "stdio.h"
#include "out.h"
typedef struct{char ddd:1;char ggg:2;};
#endif
