#ifndef KCRTROFOJRQOWICTROSDBSNNTHCFJMIFGENJELXUCAYIYVXYLBTPDGYKMIUXQPGT
#define KCRTROFOJRQOWICTROSDBSNNTHCFJMIFGENJELXUCAYIYVXYLBTPDGYKMIUXQPGT
#include "mainFrame.h"
#include "stdio.h"
#include "out.h"
#endif 
